### ISSUE TITLE
Firefox Autocomplete FIX

### ISSUE THREAD

**Issue by RockyBukake** [CosasDePuma/NameNotFound#2] opened 2019-09-29 21:23 UTC
![Screenshot from 2019-09-29 22-16-26](https://user-images.githubusercontent.com/35773324/65839696-aa1fd580-e307-11e9-9f0a-8f529588b90f.png)

Please change from type="password" to type="text" at line 78 this fixes firefox autocomplete

![Screenshot from 2019-09-29 22-16-43](https://user-images.githubusercontent.com/35773324/65839706-cae82b00-e307-11e9-8414-b52ca1f7ee4d.png)

**Comment by CosasDePuma** [comment] 2019-09-30 00:33
👌 Thanks for submit the issue!

I dont want to show the password in plane text, so I've hidden an input to "fool" browsers.
Try it now and tell me if the issue is fixed.

Tested on Firefox Quantum 69.0.1 (64-bit) Windows
Tested on Google Chrome 77.0.3865.90 (64 bits) Windows

**Comment by CosasDePuma** [comment] 2019-10-02 13:04
I will close the issue because it is considered fixed.

**Closed as completed by CosasDePuma** 2019-10-02 13:04 UTC
Labels: enhancement
